version: '3.4'

networks:
  localdev:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    networks:
      - localdev
    build: .
    ports:
      - "3306:3306"
  python:
    build: ./python
    networks:
      - localdev
    depends_on:
      - "mysql"
    links:
      - mysql:mysql

